/**
 * 扩展内部消息协议。content.js 不能 import（内容脚本非模块），
 * 因此 content.js 里用同样的字符串常量，本文件是唯一事实来源。
 */

// 页面 / 弹窗 → 后台
export const MSG = {
  GET_PUBLIC_SETTINGS: 'AITX_GET_PUBLIC_SETTINGS',
  GET_SETTINGS: 'AITX_GET_SETTINGS',
  SAVE_SETTINGS: 'AITX_SAVE_SETTINGS',
  TEST_CONNECTION: 'AITX_TEST_CONNECTION',
  TRANSLATE_TEXTS: 'AITX_TRANSLATE_TEXTS',
  TRANSLATE_ONE: 'AITX_TRANSLATE_ONE',
  SUMMARIZE: 'AITX_SUMMARIZE',
  SET_BADGE: 'AITX_SET_BADGE',
  SHOW_TRANSLATION: 'AITX_SHOW_TRANSLATION',
};

// 弹窗 → 页面
export const PAGE_CMD = {
  TOGGLE_PAGE: 'AITX_TOGGLE_PAGE',
  RESTORE_PAGE: 'AITX_RESTORE_PAGE',
  SUMMARIZE_PAGE: 'AITX_SUMMARIZE_PAGE',
  TRANSLATE_SELECTION: 'AITX_TRANSLATE_SELECTION',
  GET_STATE: 'AITX_GET_STATE',
  PING: 'AITX_PING',
};
